<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VoiceDictation.Infrastructure\VoiceDictation.Infrastructure.csproj" />
    <ProjectReference Include="..\VoiceDictation.Core\VoiceDictation.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Whisper.net.Runtime" Version="1.9.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>

</Project>
